name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Collect APK
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/Alasr.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Alasr
          path: artifacts/Alasr.apk
